# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting build performance.
ENV['COCOAPODS_DISABLE_STATS'] = '1'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_install_all_ios_pods(ios_application_path = nil)
  root_path = File.expand_path('..', File.dirname(__FILE__))
  app_path = ios_application_path || File.join(root_path, '.ios', 'Flutter', 'podhelper.rb')
  parse_allocator_path = File.join(root_path, '.ios', 'Flutter', 'parse_allocator.rb')
  File.exists?(parse_allocator_path) && load(parse_allocator_path)
  load app_path
  install_all_flutter_pods(ios_application_path)
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
